document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<title>头部导航栏</title>");
document.writeln("		<style>");
document.writeln("			body{");
document.writeln("				margin: auto;");
document.writeln("				padding:0px;");
document.writeln("			}");
document.writeln("			header{	");
document.writeln("				margin: 0px;");
document.writeln("				padding:0px;");
document.writeln("				width: 100%;");
document.writeln("				height: 60px;");
document.writeln("				//border: 0.0625rem gray solid;");
document.writeln("				//background-color: aliceblue;");
document.writeln("				background-color: white;");
document.writeln("				}");
document.writeln("			.topdiv1{");
document.writeln("				vertical-align: top;");
document.writeln("				width: 30%;");
document.writeln("				height: 60px;");
document.writeln("				display: inline-block;");
document.writeln("				//background-color: coral;");
document.writeln("			}");
document.writeln("			.toplogo{");
document.writeln("				width: 38%;");
document.writeln("				height: 45px;");
document.writeln("				margin-top:2%;");
document.writeln("				margin-left:30%;");
document.writeln("				//background-color: #40E0D0;");
document.writeln("				/*vertical-align: middle;*/");
document.writeln("			}");
document.writeln("			.topdiv2{");
document.writeln("				width: 30%;");
document.writeln("				height: 60px;");
document.writeln("				//background-color: bisque;");
document.writeln("				display: inline-block;");
document.writeln("			}");
document.writeln("		");
document.writeln("			.toptext{");
document.writeln("				border:1px #40E0D0 solid ;");
document.writeln("				border-right: none;");
document.writeln("				width: 45%;");
document.writeln("				height: 40%;");
document.writeln("				margin-top: 3.5%;");
document.writeln("				margin-left: 30%;");
document.writeln("				border-radius: 70px 0px 0px 70px;");
document.writeln("				outline:medium;");
document.writeln("			}");
document.writeln("			.topss{");
document.writeln("				");
document.writeln("				margin: 0rem;");
document.writeln("				padding: 0rem;");
document.writeln("			}");
document.writeln("			.topssimg{");
document.writeln("				vertical-align: top;");
document.writeln("				background-color: white;");
document.writeln("				border-radius:0px 70px 70px 0px ;");
document.writeln("				border: 1px #40E0D0 solid;");
document.writeln("				border-left: none;");
document.writeln("				margin-top: 3.5%;");
document.writeln("				margin-left: -2%;");
document.writeln("				width: 6%;");
document.writeln("				height: 43.5%;");
document.writeln("				display: inline-block;");
document.writeln("				");
document.writeln("			}");
document.writeln("			.topdiv3{	");
document.writeln("				vertical-align: top;");
document.writeln("				width: 30%;");
document.writeln("				height: 60px;");
document.writeln("				display: inline-block;");
document.writeln("				//background-color: burlywood;");
document.writeln("				text-align: center;");
document.writeln("			}");
document.writeln("			.topdiv3 a{");
document.writeln("				padding: 1%;");
document.writeln("				text-decoration:none;");
document.writeln("				display: inline-block;");
document.writeln("				margin-right: 10%;");
document.writeln("				margin-top: 4%;	");
document.writeln("				padding-left: 3%;");
document.writeln("				padding-right: 3%;");
document.writeln("						");
document.writeln("			}");
document.writeln("			.topa1{");
document.writeln("				background-color: crimson;");
document.writeln("				border: 0.0625rem #FFFFFF solid;");
document.writeln("				border-radius: 5px;");
document.writeln("				color: #FFFFFF;");
document.writeln("			}");
document.writeln("			.topa2{");
document.writeln("				border: 0.0625rem #40E0D0 solid;");
document.writeln("				border-radius: 5px;");
document.writeln("			}");
document.writeln("		</style>");
document.writeln("		<link rel=\'stylesheet\' href=\'css/read.css\' />");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!-- 头部栏-->");
document.writeln("		<header>");
document.writeln("			<!-- t1.logo-->");
document.writeln("			<div class=\'topdiv1\'>");
document.writeln("				<img src=\'img/logo.png\' class=\'toplogo\'>");
document.writeln("			</div>");
document.writeln("			");
document.writeln("			<!-- t2.搜索框-->");
document.writeln("			<div class=\'topdiv2\'>");
document.writeln("				<input type=\'text\' class=\'toptext\'  />");
document.writeln("				<a href=\'#\' class=\'topss\'><img src=\'img/sousuo.png\' class=\'topssimg\'></a>");
document.writeln("			</div>");
document.writeln("			<!-- t3.功能框-->");
document.writeln("			<div class=\'topdiv3\'>");
document.writeln("				<a href=\'#\'>登录</a>");
document.writeln("				<a href=\'#\' class=\'topa2\'>注册</a>");
document.writeln("				<a href=\'#\' class=\'topa1\'>写文章</a>");
document.writeln("			</div>");
document.writeln("			<br/>");
document.writeln("		</header>	 ");
document.writeln("		");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");