//网页头部直接复用脚本，CSS在newlife下CSS文件夹中header.css
document.writeln("<header>");
document.writeln("			<div id=\'header_cont\'>");
document.writeln("				");
document.writeln("				<!-- logo容器 -->");
document.writeln("				<div id=\'logo_cont\'>");
document.writeln("					<img src=\'image/logo.png\' id=\'logo_ima\'>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				<!-- 搜索框 -->");
document.writeln("				<div id=\'search_cont\'>");
document.writeln("					<input type=\'text\' name=\'\' id=\'search_input\' placeholder=\'作者/文章\'/>");
document.writeln("					<img src=\'file/icon/search.svg\' id=\'search_logo\'>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				<!-- 右侧登录等按钮 -->");
document.writeln("				<div id=\'login_operation\'>");
document.writeln("					<!-- 登录注册容器 -->");
document.writeln("					<div id=\'login_on_cont\'>");
document.writeln("						<p id=\'login_word\'>登录</p>");
document.writeln("						<p id=\'logon_word\'>注册</p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("<!-- 写作按钮 -->");
document.writeln("			<div id=\'write_but_cont\'>");
document.writeln("				<img src=\'file/icon/brush_fill_white.svg\' id=\'write_logo\'>写作");
document.writeln("			</div>");
document.writeln("		</header>");