//顶部Header复用html代码
document.writeln("<header>");
document.writeln("			<div id=\'header_cont\'>");
document.writeln("				");
document.writeln("				<!-- logo容器 -->");
document.writeln("				<a href=\'../\' target=\'_blank\'>");
document.writeln("				<div id=\'logo_cont\'>");
document.writeln("					<img src=\'../file/image/logo.png\' id=\'logo_ima\'>");
document.writeln("				</div>");
document.writeln("				</a>");
document.writeln("				");
document.writeln("				");
document.writeln("				<!-- 搜索框 -->");
document.writeln("				<form action=\'../search/\' method=\'get\'  target=\'_blank\'>");
document.writeln("				<div id=\'search_cont\'>");
document.writeln("						<input type=\'text\' id=\'search_input\' name=\'wd\' placeholder=\'作者/文章\'/>");
document.writeln("						");
document.writeln("						<!-- 搜索logo容器 -->");
document.writeln("						<div id=\'search_logo_cont\'>");
document.writeln("							<img src=\'../file/icon/search.svg\' class=\'search_logo\' id=\'search_logo\'>");
document.writeln("						</div>");
document.writeln("							<input type=\'submit\' name=\'submit\' class=\'search_logo\'  id=\'search_submit\' />");
document.writeln("				</div>");
document.writeln("				</form>");
document.writeln("				");
document.writeln("				<!-- 右侧登录等按钮 -->");
document.writeln("				<div id=\'login_operation\'>");
document.writeln("					<!-- 登录注册容器 -->");
document.writeln("					<div id=\'login_on_cont\'>");
document.writeln("						<a href=\'../login/\' target=\'_blank\'><p id=\'login_word\'>登录</p></a>");
document.writeln("						<a href=\'../login/\' target=\'_blank\'><p id=\'logon_word\'>注册</p></a>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("					<!-- 右侧登录后显示的个人框 -->");
document.writeln("					<div id=\'user_head_cont\'>");
document.writeln("						<a id=\'user_head_href\'><div id=\'read_dot\'></div><div id=\'user_head_img_cont\'><img src=\'../userFile/\'+userId+\'/headPortrait.jpg\' id=\'user_head\'></div></a>");
document.writeln("						");
document.writeln("						<!-- 个人操作框 -->");
document.writeln("						<div id=\'header_operation_cont\'>");
document.writeln("							<p id=\'first_operation_transparent\'></p>");
document.writeln("							<a target=\'_blank\' id=\'user_page_href\'><p class=\'header_operation\'><img src=\'../file/icon/people_fill.svg\' class=\'header_operation_logo\'>我的空间</p></a>");
document.writeln("							<p class=\'header_operation\'><img src=\'../file/icon/mail_fill.svg\' class=\'header_operation_logo\'>我的来信<span id=\'read_dot_mail\'></span></p>");
document.writeln("							<p class=\'header_operation\' id=\'sign_out_operation\'><img src=\'../file/icon/close.svg\' class=\'header_operation_logo\' id=\'last_header_operation_logo\'>退出登录</p>");
document.writeln("							<p id=\'last_operation_transparent\'></p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				");
document.writeln("			</div>");
document.writeln("			");
document.writeln("			<!-- 写作按钮 -->");
document.writeln("			<a href=\'../write/\' target=\'_blank\'><div id=\'write_but_cont\'>");
document.writeln("				<img src=\'../file/icon/brush_fill_white.svg\' id=\'write_logo\'>写作");
document.writeln("			</div>");
document.writeln("			</a>");
document.writeln("			");
document.writeln("		</header>");
